<a href="https://colab.research.google.com/github/LucyAlex12/-Arinze-Chioma-Lucy/blob/main/MyAssignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **My Assignment**

**Section 1: Libraries**

Question 1

In my own words , Library in programming is like a container that has codes in it that can be used during programming , so as to make programming easier and faster rather than having to write a particular code or function , you house them in a library so they can be re used.

Question 2

The two libraries that have been introduced in our lectures are Numpy and Pandas. Numpy is used when dealing with numeric data, while Pandas is used when dealing with datasets.

**Section 2: NumPy**

Question 3

In [9]:
import numpy as np
my_numbers = np.array([1, 2, 3, 4, 5, 6])

print(my_numbers)

[1 2 3 4 5 6]

**Section 3: Pandas - Building and Exploring a Dataset**

In [10]:
import pandas as pd
data = {
    "StudentID": [101, 102, 203, 204, 205, 206, 207, 208],
    "Name": ["Ose", "Chidi", "Cheta", "Emma", "Kc", "Sope", "Onyinye", "Opeyemi"],
    "Age": [20, 21, 19, 22, 20, 21, 23, 20],
    "Department": ["Mass comm", "Politcal Science", "Engineering", "Microbiology", "Law", "Microbiology", "Engineering", "Mass comm"],
    "Score": [75, 88, 92, 85, 70, 95, 89, 78],
    "Grade": ["B", "A", "A", "B", "C", "A", "A", "B"]
}

df = pd.DataFrame(data)
df

   StudentID     Name  Age        Department  Score Grade
0        101      Ose   20         Mass comm     75     B
1        102    Chidi   21  Politcal Science     88     A
2        203    Cheta   19       Engineering     92     A
3        204     Emma   22      Microbiology     85     B
4        205       Kc   20               Law     70     C
5        206     Sope   21      Microbiology     95     A
6        207  Onyinye   23       Engineering     89     A
7        208  Opeyemi   20         Mass comm     78     B

In [11]:
df.head()
df.tail(3)

   StudentID     Name  Age    Department  Score Grade
5        206     Sope   21  Microbiology     95     A
6        207  Onyinye   23   Engineering     89     A
7        208  Opeyemi   20     Mass comm     78     B

In [12]:
df.shape

(8, 6)

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   StudentID   8 non-null      int64
 1   Name        8 non-null      object
 2   Age         8 non-null      int64
 3   Department  8 non-null      object
 4   Score       8 non-null      int64
 5   Grade       8 non-null      object
dtypes: int64(3), object(3)
memory usage: 516.0+ bytes

In [14]:
df["Department"].unique()
df["Department"].nunique()

df["Grade"].unique()
df["Grade"].nunique()

3

I really found it interesting how easy Pandas made everything. Like, just small small code and you can already see and understand your data properly. I was also surprised at how fast I could check things like unique values and the size of the dataset without stress.